objects/Account.object
<CustomObject>
    <fields>
        <fullName>Region__c</fullName>
        <description>Account regions for the Machinery sales teams.</description>
        <label>Region</label>
        <type>Picklist</type>
        <valueSet>
            <valueSetDefinition>
                <value>
                    <fullName>East</fullName>
                </value>
                <value>
                    <fullName>West</fullName>
                </value>
                <value>
                    <fullName>Midwest</fullName>
                </value>
                <value>
                    <fullName>Mexico</fullName>
                </value>
                <value>
                    <fullName>Latin America</fullName>
                </value>
                <value>
                    <fullName>ME/Africa</fullName>
                </value>
                <value>
                    <fullName>Brazil</fullName>
                </value>
                <value>
                    <fullName>Germany East</fullName>
                </value>
                <value>
                    <fullName>Germany Middle-West</fullName>
                </value>
                <value>
                    <fullName>Germany North</fullName>
                </value>
                <value>
                    <fullName>Germany South-East</fullName>
                </value>
                <value>
                    <fullName>Germany South-West</fullName>
                </value>
                <value>
                    <fullName>Germany West</fullName>
                </value>
                <value>
                    <fullName>EXPORT SAARC</fullName>
                </value>
                <value>
                    <fullName>EXPORT WEST AFRICA - 2</fullName>
                </value>
                <value>
                    <fullName>EXPORT EAST AFRICA</fullName>
                </value>
                <value>
                    <fullName>EXPORT MIDDLE EAST</fullName>
                </value>
                <value>
                    <fullName>EXPORT SOUTH CENTRAL AFRICA</fullName>
                </value>
                <value>
                    <fullName>EXPORT LATIN AMERICA</fullName>
                </value>
                <value>
                    <fullName>AHMEDABAD</fullName>
                </value>
                <value>
                    <fullName>EXPORT OMNI</fullName>
                </value>
                <value>
                    <fullName>EXPORT WEST AFRICA - 1</fullName>
                </value>
                <value>
                    <fullName>BLOW MOULDING</fullName>
                </value>
                <value>
                    <fullName>EXPORT AFRICA</fullName>
                </value>
                <value>
                    <fullName>EXPORT ASIA</fullName>
                </value>
                <value>
                    <fullName>EXPORT SAARC- NOT APPLICABLE</fullName>
                </value>
                <value>
                    <fullName>EXPORT WEST AFRICA</fullName>
                </value>
                <value>
                    <fullName>OTHERS</fullName>
                </value>
                <value>
                    <fullName>MUMBAI</fullName>
                </value>
                <value>
                    <fullName>DELHI</fullName>
                </value>
            </valueSetDefinition>
        </valueSet>
    </fields>
    <sharingModel>Private</sharingModel>
</CustomObject>

objects/Asset.object
<CustomObject>
    <fields>
        <fullName>Date_Shipped__c</fullName>
        <description>Date on which this product was shipped to the customer originally</description>
        <inlineHelpText>Date on which this product was shipped to the customer originally</inlineHelpText>
        <label>Date Shipped</label>
        <type>Date</type>
    </fields>
    <fields>
        <fullName>Frame_Size__c</fullName>
        <label>Frame Size</label>
        <length>40</length>
        <type>Text</type>
    </fields>
    <fields>
        <fullName>Model_Code__c</fullName>
        <label>Model Code</label>
        <length>40</length>
        <type>Text</type>
    </fields>
    <fields>
        <fullName>Model_Descriptions__c</fullName>
        <label>Model Descriptions</label>
        <length>100</length>
        <type>Text</type>
    </fields>
    <fields>
        <fullName>Sales_Order_Number__c</fullName>
        <label>Sales Order Number</label>
        <length>100</length>
        <type>Text</type>
    </fields>
    <fields>
        <fullName>Service_Area_Region__c</fullName>
        <formula>TEXT( Account.Service_Region__c )</formula>
        <formulaTreatBlanksAs>BlankAsZero</formulaTreatBlanksAs>
        <label>Service Area/Region</label>
        <type>Text</type>
    </fields>
    <fields>
        <fullName>Tonnage_Description__c</fullName>
        <label>Tonnage Description</label>
        <length>100</length>
        <type>Text</type>
    </fields>
    <recordTypes>
        <fullName>Machine</fullName>
        <active>true</active>
        <description>Machines owned by Accounts</description>
        <label>Machine</label>
    </recordTypes>
    <sharingModel>ControlledByParent</sharingModel>
</CustomObject>

objects/ERN__c.object
<CustomObject>
    <description>Engineering Review Note</description>
    <fields>
        <fullName>Account__c</fullName>
        <deleteConstraint>SetNull</deleteConstraint>
        <label>Account</label>
        <referenceTo>Account</referenceTo>
        <relationshipLabel>ERN</relationshipLabel>
        <relationshipName>ERN</relationshipName>
        <type>Lookup</type>
    </fields>
    <fields>
        <fullName>Asset__c</fullName>
        <deleteConstraint>SetNull</deleteConstraint>
        <description>Master Asset for which ERN is generated.</description>
        <inlineHelpText>Master Asset for which ERN is generated.</inlineHelpText>
        <label>Asset</label>
        <referenceTo>Asset</referenceTo>
        <relationshipLabel>ERN</relationshipLabel>
        <relationshipName>ERN</relationshipName>
        <type>Lookup</type>
    </fields>
    <fields>
        <fullName>Category__c</fullName>
        <description>Category for Field Service ERNs.</description>
        <label>Category</label>
        <type>MultiselectPicklist</type>
        <valueSet>
            <restricted>true</restricted>
            <valueSetDefinition>
                <value>
                    <fullName>IU conversion</fullName>
                </value>
                <value>
                    <fullName>Hydro Motor</fullName>
                </value>
                <value>
                    <fullName>Pump</fullName>
                </value>
                <value>
                    <fullName>Power pack replacement</fullName>
                </value>
                <value>
                    <fullName>Drive/Motor</fullName>
                </value>
                <value>
                    <fullName>Software</fullName>
                </value>
                <value>
                    <fullName>Core</fullName>
                </value>
                <value>
                    <fullName>Air Ejection</fullName>
                </value>
                <value>
                    <fullName>Back pressure</fullName>
                </value>
                <value>
                    <fullName>Robot</fullName>
                </value>
                <value>
                    <fullName>RMS</fullName>
                </value>
                <value>
                    <fullName>OPC</fullName>
                </value>
                <value>
                    <fullName>MGO</fullName>
                </value>
                <value>
                    <fullName>Ejector</fullName>
                </value>
                <value>
                    <fullName>EOF</fullName>
                </value>
                <value>
                    <fullName>Hopper/Sliding assembly</fullName>
                </value>
                <value>
                    <fullName>Part separator</fullName>
                </value>
                <value>
                    <fullName>Part drop detect</fullName>
                </value>
                <value>
                    <fullName>Auxiliary interface</fullName>
                </value>
                <value>
                    <fullName>Gate &amp; Gate Frame</fullName>
                </value>
                <value>
                    <fullName>Mould Height Reduction</fullName>
                </value>
                <value>
                    <fullName>RAM spacer</fullName>
                </value>
                <value>
                    <fullName>Retrofitment-Control</fullName>
                </value>
                <value>
                    <fullName>Retrofitment-Servo</fullName>
                </value>
                <value>
                    <fullName>Retrofitment/Refurbishment</fullName>
                </value>
                <value>
                    <fullName>Heater &amp; Heater blowers</fullName>
                </value>
                <value>
                    <fullName>Increase Mould Carrying Capacity</fullName>
                </value>
                <value>
                    <fullName>NSOV</fullName>
                </value>
                <value>
                    <fullName>Electrical part replacement</fullName>
                </value>
                <value>
                    <fullName>Heat Exchanger</fullName>
                    <isActive>false</isActive>
                    <label>Heat Exchanger</label>
                </value>
            </valueSetDefinition>
        </valueSet>
    </fields>
    <fields>
        <fullName>Control_Rack_Details__c</fullName>
        <description>Control Rack Details/95_1 Page</description>
        <inlineHelpText>Control Rack Details/95_1 Page</inlineHelpText>
        <label>Control Rack Details</label>
        <length>255</length>
        <type>Text</type>
    </fields>
    <fields>
        <fullName>Hydraulic_Circuit_Number__c</fullName>
        <description>Hydraulic Circuit Number of Asset.</description>
        <inlineHelpText>Hydraulic Circuit Number of Asset.</inlineHelpText>
        <label>Hydraulic Circuit Number</label>
        <length>50</length>
        <type>Text</type>
    </fields>
    <fields>
        <fullName>Injection_Unit__c</fullName>
        <label>Injection Unit</label>
        <length>100</length>
        <type>Text</type>
    </fields>
    <fields>
        <fullName>Machine_Modifications_in_Field_Remarks__c</fullName>
        <label>Machine Modifications in Field/Remarks</label>
        <length>1000</length>
        <type>LongTextArea</type>
    </fields>
    <fields>
        <fullName>Product_Family__c</fullName>
        <formula>IF( NOT(ISBLANK( Product_Line__c )) &amp;&amp; (Product_Line__c = &quot;ELEKTRON&quot;),&quot;Electric&quot;,
IF( NOT(ISBLANK( Product_Line__c )) &amp;&amp; (Product_Line__c = &quot;HDACCU&quot; || Product_Line__c = &quot;HDSRV&quot; || Product_Line__c == &quot;HDSRV2K&quot; || Product_Line__c == &quot;HYDRN&quot; || Product_Line__c = &quot;OMG&quot; || Product_Line__c = &quot;OMG3C&quot; || Product_Line__c = &quot;OMG3CSRV&quot; || Product_Line__c = &quot;OMGBT&quot; || Product_Line__c = &quot;OMGRPVC&quot; || Product_Line__c = &quot;OMGRPVCSRV&quot; || Product_Line__c = &quot;OMGSB&quot; || Product_Line__c = &quot;OMGSBSRV&quot; || Product_Line__c = &quot;OMGSRV&quot; || Product_Line__c = &quot;OMGTC&quot; || Product_Line__c = &quot;OMGTCSRV&quot; || Product_Line__c = &quot;HDSRVRP&quot; || Product_Line__c = &quot;MH&quot; || Product_Line__c = &quot;MHT&quot;),&quot;RAM&quot;,
IF( NOT(ISBLANK( Product_Line__c )) &amp;&amp; (Product_Line__c = &quot;MAXIMA&quot; || Product_Line__c = &quot;MAXIMASRV&quot; || Product_Line__c == &quot;CMS&quot; || Product_Line__c == &quot;MPs&quot; || Product_Line__c = &quot;MPs2K&quot; || Product_Line__c = &quot;MPS2K&quot;),&quot;Maxima&quot;,
IF( NOT(ISBLANK( Product_Line__c )) &amp;&amp; (Product_Line__c = &quot;MAGTOG&quot; || Product_Line__c = &quot;MTSRV&quot; || Product_Line__c == &quot;MTACCU&quot; || Product_Line__c == &quot;MTSRV2K&quot; || Product_Line__c = &quot;MTCPVC&quot; || Product_Line__c = &quot;MTCPVCS&quot; || Product_Line__c = &quot;NVSRV&quot; || Product_Line__c = &quot;NVSRVRP&quot; || Product_Line__c = &quot;PETLINE&quot; || Product_Line__c = &quot;PETLINESRV&quot; || Product_Line__c = &quot;MTUSSRV&quot; || Product_Line__c = &quot;MTCESRV&quot; || Product_Line__c = &quot;SIG&quot; || Product_Line__c = &quot;DELTA&quot; || Product_Line__c = &quot;QTSRV&quot; || Product_Line__c == &quot;QTUSSRV&quot; || Product_Line__c == &quot;QTCESRV&quot; || Product_Line__c == &quot;QTACCU&quot;),&quot;Toggle&quot;,null))))</formula>
        <label>Product Family</label>
        <type>Text</type>
    </fields>
    <fields>
        <fullName>Product_Line__c</fullName>
        <label>Product Line</label>
        <length>50</length>
        <type>Text</type>
    </fields>
    <fields>
        <fullName>Region__c</fullName>
        <label>Region</label>
        <type>Picklist</type>
        <valueSet>
            <restricted>true</restricted>
            <valueSetDefinition>
                <value>
                    <fullName>Ahmedabad</fullName>
                </value>
                <value>
                    <fullName>Bengaluru</fullName>
                </value>
                <value>
                    <fullName>Chandigarh</fullName>
                </value>
                <value>
                    <fullName>Chennai</fullName>
                </value>
                <value>
                    <fullName>Delhi</fullName>
                </value>
                <value>
                    <fullName>Hyderabad</fullName>
                </value>
                <value>
                    <fullName>Kolkata</fullName>
                </value>
                <value>
                    <fullName>Mumbai</fullName>
                </value>
                <value>
                    <fullName>Pune</fullName>
                </value>
                <value>
                    <fullName>Export-India</fullName>
                </value>
                <value>
                    <fullName>Haridwar</fullName>
                </value>
                <value>
                    <fullName>Vapi</fullName>
                </value>
                <value>
                    <fullName>Intercompany</fullName>
                </value>
                <value>
                    <fullName>Great Lakes</fullName>
                </value>
                <value>
                    <fullName>Bangalore</fullName>
                    <isActive>false</isActive>
                    <label>Bangalore</label>
                </value>
                <value>
                    <fullName>Export</fullName>
                    <isActive>false</isActive>
                    <label>Export</label>
                </value>
            </valueSetDefinition>
        </valueSet>
    </fields>
    <fields>
        <fullName>Software_Version__c</fullName>
        <description>Software Version of Asset.</description>
        <inlineHelpText>Software Version of Asset</inlineHelpText>
        <label>Software Version</label>
        <length>100</length>
        <type>Text</type>
    </fields>
    <fields>
        <fullName>Tonnage__c</fullName>
        <label>Tonnage</label>
        <length>50</length>
        <type>Text</type>
    </fields>
    <label>ERN</label>
    <nameField>
        <label>ERN Name</label>
        <type>Text</type>
    </nameField>
    <pluralLabel>ERN</pluralLabel>
    <sharingModel>ReadWrite</sharingModel>
</CustomObject>

classes/FieldServiceERNCreation.cls
public class FieldServiceERNCreation {
    
    @AuraEnabled
    Public Static Asset getAsset(Id recordId){
        Asset Asst = [Select Id,Name,Sales_Order_Number__c,Account.Name,Tonnage_Description__c,Date_Shipped__c,Frame_Size__c,Model_Descriptions__c,Service_Area_Region__c From Asset where Id = : recordId];
        return Asst;
    }
    @AuraEnabled
    public static Map<String, String> getLabels(Id recordId) {
        
        String type='Asset';
        Map<String, Schema.SObjectType> schemaMap = Schema.getGlobalDescribe();
        Schema.SObjectType AsstSchema = schemaMap.get(type);
        Map<String, Schema.SObjectField> fieldMap = AsstSchema.getDescribe().fields.getMap();
        Map<String, String> fieldsLabel = new Map<String, String>();
        
        for (String fieldName: fieldMap.keySet()) {
            //System.debug(fieldName);
            //System.debug(fieldMap.get(fieldname).getDescribe().getLabel());
            fieldsLabel.put(fieldName, fieldMap.get(fieldname).getDescribe().getLabel());
        }
        return fieldsLabel;
    }
    /*@AuraEnabled        
public static List<String> getPickListValuesIntoList(String objectType, String selectedField){
List<String> pickListValuesList = new List<String>();
Schema.SObjectType convertToObj = Schema.getGlobalDescribe().get(objectType);
Schema.DescribeSObjectResult res = convertToObj.getDescribe();
Schema.DescribeFieldResult fieldResult = res.fields.getMap().get(selectedField).getDescribe();
List<Schema.PicklistEntry> ple = fieldResult.getPicklistValues();
for( Schema.PicklistEntry pickListVal : ple){
pickListValuesList.add(pickListVal.getLabel());
}     
return pickListValuesList;
}*/
    @AuraEnabled
    public static List <String> getPiklistValues(string fieldName) {
        List<String> plValues = new List<String>();
        
        //Get the object type from object name. Here I've used custom object Book.
        Schema.SObjectType objType = Schema.getGlobalDescribe().get('ERN__c');
        
        //Describe the sObject using its object type.
        Schema.DescribeSObjectResult objDescribe = objType.getDescribe();
        
        //Get the specific field information from field name. Here I've used custom field Category__c of Book object.
        Schema.DescribeFieldResult objFieldInfo = objDescribe.fields.getMap().get(fieldName).getDescribe();
        
        //Get the picklist field values.
        List<Schema.PicklistEntry> picklistvalues = objFieldInfo.getPicklistValues();
        
        //Add the picklist values to list.
        for(Schema.PicklistEntry plv: picklistvalues) {
            plValues.add(plv.getValue());
        }
        plValues.sort();
        return plValues;
    }
    /*@AuraEnabled
public static Boolean getERNCreationCriteria(Id AssetId, Decimal TotalCores, Decimal TotalMGO, Decimal TotalAirEje){
System.debug('AssetId--> '+ AssetId);
Boolean IsAlert = false;
Asset asst = [Select Id, Date_Shipped__c,Model_Descriptions__c, SerialNumber From Asset where id = : AssetId];
if(asst.Date_Shipped__c >= Date.valueOf('2007-01-01') && !asst.Model_Descriptions__c.toLowercase().contains('maxima') && (TotalCores <= 3 && TotalCores > 0) || (TotalMGO <= 4 && TotalMGO > 0) || (TotalAirEje <= 4 && TotalAirEje > 0)){
IsAlert = true;
}
System.debug('IsAlert--> '+ IsAlert);
Return IsAlert;
}*/
    @AuraEnabled
    public static Id createERNRecord (ERN__c Ern, Id AssetId){
        Asset Asst = [Select Id,AccountId, Date_Shipped__c,Model_Descriptions__c, SerialNumber, Tonnage_Description__c, Frame_Size__c, Model_Code__c,Service_Area_Region__c  From Asset where id = : AssetId];
        Id recTypeId = Schema.SObjectType.ERN__c.getRecordTypeInfosByName().get('Open Service ERN').getRecordTypeId();
        ERN__c e = new ERN__c();
        
        e = Ern;
        
        e.Asset__c = AssetId;
        e.Account__c = asst.AccountId;
        e.Product_Line__c = asst.Model_Code__c;
        e.Tonnage__c = asst.Tonnage_Description__c;
        e.Injection_Unit__c = asst.Frame_Size__c;
        e.RecordTypeId = recTypeId;
        e.Region__c = asst.Service_Area_Region__c;
        System.debug('Product Line'+asst.Model_Code__c);
        System.debug('ERN Product Family'+e.Product_Family__c);
        insert e;
        return e.Id;
    }
    @AuraEnabled
    public static List<ContentDocument> getUploadedFiles (Id ErnId){
        system.debug('getUploadedFiles Started');
        Set<Id> DocIds = new set<Id>();
        for(ContentDocumentLink cdl :[Select Id, LinkedEntityId, ContentDocumentId FROM ContentDocumentLink WHERE LinkedEntityId =: ErnId]){
            DocIds.add(cdl.ContentDocumentId);
        }
        List<ContentDocument> Docs = [Select Id, title from ContentDocument where id In : DocIds];
        Return Docs;
    }
    @AuraEnabled
    public static List<ContentDocument> DeleteSelectedFile (Id DocId, Id ErnId){
        ContentDocument DelCondoc = [Select id From ContentDocument Where id =: DocId];
        Delete DelCondoc;
        Set<Id> DocIds = new set<Id>();
        for(ContentDocumentLink cdl :[Select Id, LinkedEntityId, ContentDocumentId FROM ContentDocumentLink WHERE LinkedEntityId =: ErnId]){
            DocIds.add(cdl.ContentDocumentId);
        }
        List<ContentDocument> Docs = [Select Id, title from ContentDocument where id In : DocIds];
        Return Docs;
    }
    
    @AuraEnabled 
    public static List<sObject> fetchAsset(String searchKeyWord,String ern_id){
        System.debug('****'+ern_id);
        String sreachkey='%'+searchKeyWord+'%';
        List<ERN__c> er=[select id,Account__c from ERN__c where id=:ern_id];
        List<sObject> ls=[select id,name,Sales_Order_Number__c from Asset where Account.Id=:er[0].Account__c AND Sales_Order_Number__c Like: sreachkey];
        return ls;
    }
    
    @AuraEnabled
    public static List<ERN_Assets__c> insertERN_Asset(String ern_data,String ern_id){
        List<String> ls=(List<String>)System.JSON.deserialize(ern_data, List<String>.class);
        Map<String,String> m=new Map<String,String>();
        Map<String,String> m2=new Map<String,String>();
        for(String ls_obj:ls){
            List<String> tmp=ls_obj.split(':');
            m.put(tmp[0],tmp[1]);
        }
        List<Asset> ls_asset=[select id,Name from Asset where Name in: m.keySet()];
        for(Asset ast:ls_asset){
            m2.put(ast.Name,ast.Id);
        }
        
        List<ERN_Assets__c> list_ERN_Asset=new List<ERN_Assets__c>();
        for(String st:m.keySet()){
            List<String> extraDetail=m.get(st).split(';');
            System.debug('exta'+extraDetail);
            /*extraDetail is List will contain the detail which is fetch from component 
extraDetail[0] will contain software Version
extraDetail[1] will contain control Rock
extraDetail[2] will contain Electrical Circuit
extraDetail[3] will contain Hydraulic Circuit Number
extraDetail[4] will contain Machine Modifications in Field/Remarks
*/
            ERN_Assets__c e1=new ERN_Assets__c();
            e1.Asset__c=m2.get(st);
            e1.ERN__c=ern_id;
            
            if(extraDetail.size()!=5){
                try{
                    e1.Software_Version__c=extraDetail[1];
                }
                catch(Exception ex){
                    e1.Software_Version__c='';
                }
                try{
                    e1.Control_Rack_Details__c=extraDetail[2];
                }
                catch(Exception ex){
                    e1.Control_Rack_Details__c='';
                }
                try{
                    e1.Electrical_Circuit__c=extraDetail[3];
                }
                catch(Exception ex){
                    e1.Electrical_Circuit__c='';
                        }
                try{
                    e1.Hydraulic_Circuit_Number__c=extraDetail[4];
                }
                catch(Exception ex){
                    e1.Hydraulic_Circuit_Number__c='';
                }
                try{
                    e1.Machine_Modifications_in_Field_Remarks__c=extraDetail[5];
                }
                catch(Exception ex){
                    e1.Machine_Modifications_in_Field_Remarks__c='';
                }
            }
            else if(extraDetail.size()!=5){
                e1.Software_Version__c=extraDetail[1];
                e1.Control_Rack_Details__c=extraDetail[2];
                e1.Electrical_Circuit__c=extraDetail[3];
                e1.Hydraulic_Circuit_Number__c=extraDetail[4];
                e1.Machine_Modifications_in_Field_Remarks__c=extraDetail[5];
            }
            
            
            list_ERN_Asset.add(e1);
        }
        insert list_ERN_Asset;
        List<ERN_Assets__c> ern_Asset_List=[Select Id,Asset__r.Name,ERN__r.Name,Asset__r.Sales_Order_Number__c,Asset__r.Account.Name from ERN_Assets__c where id in: list_ERN_Asset];
        System.debug('+++'+list_ERN_Asset);
        System.debug('+++'+m2);
        System.debug('+++'+ls);
        System.debug('+++'+ern_Asset_List);
        return ern_Asset_List;	
    }
    
}